// Code generated by tygo. DO NOT EDIT.

//////////
// source: handlers.go

export interface AlertHandler {
}
export interface ImportHandler {
}
export interface ErrorResponse {
  error: string;
  code?: any /* types.ErrorCode */;
  details?: { [key: string]: any};
}
export interface ValidationError {
  Field: string;
  Message: string;
}
export interface SuccessResponse {
  message: string;
  data?: any;
}
export interface PaginationRequest {
  Page: number /* int */;
  PageSize: number /* int */;
}
export interface ListEventsRequest {
  Page: number /* int */;
  PageSize: number /* int */;
  Levels: number /* int */[];
  EventIDs: number /* int32 */[];
  LogNames: string[];
  Sources: string[];
  Users: string[];
  Computers: string[];
  StartTime: string;
  EndTime: string;
  SortBy: string;
  SortOrder: string;
}
export interface ListEventsResponse {
  events: (any /* types.Event */ | undefined)[];
  total: number /* int64 */;
  page: number /* int */;
  page_size: number /* int */;
  total_pages: number /* int */;
}
export interface SearchEventsRequest {
  keywords: string;
  keyword_mode: string;
  regex: boolean;
  event_ids: number /* int32 */[];
  levels: number /* int */[];
  log_names: string[];
  sources: string[];
  users: string[];
  computers: string[];
  start_time: string;
  end_time: string;
  page: number /* int */;
  page_size: number /* int */;
  sort_by: string;
  sort_order: string;
  highlight: boolean;
}
export interface ExportRequest {
  format: string; // "json" | "csv" | "excel"
  filters: ExportFilters;
}
export interface ExportFilters {
  event_ids: number /* int32 */[];
  levels: number /* int */[];
  log_names: string[];
  computers: string[];
  users: string[];
  start_time: string;
  end_time: string;
  keywords: string;
  limit: number /* int */;
}
export interface ExportResponse {
  success: boolean;
  total: number /* int */;
  message?: string;
}
export interface ListAlertsResponse {
  alerts: (any /* types.Alert */ | undefined)[];
  total: number /* int64 */;
  page: number /* int */;
  page_size: number /* int */;
  total_pages: number /* int */;
}
export interface RunAnalysisResponse {
  success: boolean;
  alerts_created: number /* int */;
  events_analyzed: number /* int */;
  rules_executed: number /* int */;
  duration: string;
  errors?: string[];
}
export interface AlertWithDetails {
  Alert?: any /* types.Alert */;
  explanation: string;
  recommendation: string;
  real_case: string;
  keywords: string;
  matched_events?: (any /* types.Event */ | undefined)[];
}
export interface ResolveAlertRequest {
  notes: string;
}
export interface MarkFalsePositiveRequest {
  reason: string;
}
export interface BatchAlertActionRequest {
  ids: number /* int64 */[];
  action: string;
  notes: string;
  reason: string;
}
export interface ImportRequest {
  files: string[];
  alert_on_import: boolean;
  enabled_formats: string[];
  skip_patterns: string[];
}
export interface TimelineHandler {
}
export interface TimelineEntry {
  id: number /* int64 */;
  timestamp: string /* RFC3339 */;
  type: string; // "event" or "alert"
  event_id?: number /* int32 */;
  alert_id?: number /* int64 */;
  level?: string;
  source?: string;
  message: string;
  severity?: string;
  rule_name?: string;
  mitre_attack?: string[];
  computer?: string;
  log_name?: string;
  event_db_ids?: number /* int64 */[];
}
export interface TimelineResponse {
  entries: (TimelineEntry | undefined)[];
  total_count: number /* int */;
  event_count: number /* int */;
  alert_count: number /* int */;
  has_more: boolean;
  next_offset?: number /* int */;
}
export interface TimelineStats {
  total_events: number /* int64 */;
  total_alerts: number /* int64 */;
  by_level: { [key: string]: number /* int64 */};
  by_category: { [key: string]: number /* int64 */};
  by_source: { [key: string]: number /* int64 */};
  top_event_ids: { [key: number /* int32 */]: number /* int64 */};
  time_range: string;
  attack_chains: number /* int */;
}
export interface AttackChainInfo {
  id: string;
  name: string;
  technique: string;
  tactic: string;
  severity: string;
  event_count: number /* int */;
  start_time: string /* RFC3339 */;
  end_time: string /* RFC3339 */;
}

//////////
// source: handlers_analyze.go

export interface AnalyzeHandler {
}
export interface AnalyzeRequest {
  type: string;
  start_time: string;
  end_time: string;
  hours: number /* int */;
  limit: number /* int */;
  offset: number /* int */;
}
export interface AnalyzeFinding {
  description: string;
  severity: string;
  score: number /* float64 */;
  rule_name?: string;
  mitre_attack?: string[];
  metadata?: { [key: string]: any};
  evidence?: EvidenceItem[];
}
export interface EvidenceItem {
  event_id: number /* int32 */;
  timestamp: string;
  user: string;
  computer: string;
  message: string;
}
export interface Pagination {
  limit: number /* int */;
  offset: number /* int */;
  total: number /* int64 */;
}
export interface AnalyzeResult {
  type: string;
  severity: string;
  score: number /* float64 */;
  summary: string;
  findings: AnalyzeFinding[];
  timestamp: number /* int64 */;
  pagination?: Pagination;
}
export interface AnalyzerRuleInfo {
  name: string;
  type: string;
  enabled: boolean;
  description: string;
  severity: string;
  score: number /* float64 */;
  mitre_attack: string[];
  event_ids: number /* int32 */[];
  thresholds: { [key: string]: number /* int */};
  patterns: string[];
  whitelist: string[];
  technique: string;
  category: string;
}
export interface AnalyzerRuleUpdate {
  name: string;
  enabled: boolean;
  event_ids?: number /* int32 */[];
  thresholds?: { [key: string]: number /* int */};
  patterns?: string[];
  whitelist?: string[];
}

//////////
// source: handlers_collect.go

export interface CollectHandler {
}
/**
 * LogChannel 日志通道
 */
export interface LogChannel {
  name: string;
  category: string;
  log_path?: string;
}
export interface LogCollectResponse {
  status: string;
  message: string;
  output_path?: string;
  event_count?: number /* int */;
  hash?: string;
  duration?: string;
  errors?: string[];
  collected_items?: { [key: string]: number /* int */};
  success_count: number /* int */;
  failed_count: number /* int */;
}
export interface LogCollectRequest {
  sources: string[];
  formats: string[];
  options: LogCollectOptions;
}
export interface LogCollectOptions {
  workers: number /* int */;
  include_prefetch: boolean;
  include_registry: boolean;
  include_startup: boolean;
  include_system_info: boolean;
  include_shimcache: boolean;
  include_amcache: boolean;
  include_userassist: boolean;
  include_usn_journal: boolean;
  include_tasks: boolean;
  include_logs: boolean;
  include_processes: boolean;
  include_network: boolean;
  include_dlls: boolean;
  include_drivers: boolean;
  include_users: boolean;
  compress: boolean;
  calculate_hash: boolean;
  output_path: string;
}
export interface LogImportRequest {
  files: string[];
  alert_on_import: boolean;
}
export interface CollectStatus {
  status: string;
  progress: number /* int */;
  message: string;
  output_path?: string;
  files_count?: number /* int */;
  duration?: string;
}
export interface Evtx2CsvRequest {
  file_paths: string[];
  output_dir: string;
  limit: number /* int */;
  include_xml: boolean;
  calculate_hash: boolean;
}
export interface Evtx2CsvResponse {
  success: boolean;
  results: Result[];
  total_events: number /* int */;
  total_files: number /* int */;
  failed_files: number /* int */;
  errors?: string[];
}
export interface Result {
  input_path: string;
  output_path: string;
  event_count: number /* int */;
  error?: string;
}

//////////
// source: handlers_correlation.go

export interface CorrelationHandler {
}
export interface CorrelationRequest {
  time_window: string;
  rules: string[];
}
export interface CorrelationResponse {
  rule_name: string;
  severity: string;
  event_count: number /* int */;
  start_time: string /* RFC3339 */;
  end_time: string /* RFC3339 */;
  description: string;
}

//////////
// source: handlers_dashboard.go

export interface DashboardHandler {
}
export interface CollectionStatsResponse {
  total_events: number /* int64 */;
  total_size: string;
  sources: { [key: string]: number /* int64 */};
  last_import: string;
}

//////////
// source: handlers_forensics.go

export interface ForensicsHandler {
}
export interface HashRequest {
  path: string;
}
export interface SignatureRequest {
  path: string;
}
export interface CollectRequest {
  type: string;
  output_path: string;
  collect_registry: boolean;
  collect_prefetch: boolean;
  collect_shimcache: boolean;
  collect_amcache: boolean;
  collect_userassist: boolean;
  collect_tasks: boolean;
  collect_logs: boolean;
}
export interface HashResponse {
  status?: string;
  error?: string;
  file_path?: string;
  sha256?: string;
  md5?: string;
  sha1?: string;
  size?: number /* int64 */;
}
export interface SignatureResponse {
  status?: string;
  error?: string;
  signed: boolean;
  signer?: string;
  issuer?: string;
  thumbprint?: string;
  not_before?: string /* RFC3339 */;
  not_after?: string /* RFC3339 */;
}
export interface CollectResponse {
  id: string;
  type: string;
  status: string;
  output_path: string;
  collected_at: string /* RFC3339 */;
  message: string;
}

//////////
// source: handlers_live.go

export interface LiveHandler {
}
export interface LiveEventMessage {
  type: string;
  data: any;
}
export interface LiveStats {
  total_events: number /* int64 */;
  events_per_sec: number /* float64 */;
  alerts: number /* int64 */;
  uptime: string;
  timestamp: string /* RFC3339 */;
}

//////////
// source: handlers_logs.go

export interface LogsHandler {
}

//////////
// source: handlers_multi.go

export interface MultiHandler {
}
export interface MachineInfo {
  id: string;
  name: string;
  ip: string;
  domain: string;
  role: string;
  os_version: string;
  last_seen: string;
}
export interface CrossMachineActivity {
  user: string;
  machine_count: number /* int */;
  machines: string[];
  login_count: number /* int */;
  suspicious: boolean;
  severity: string;
  recommendation: string;
}
export interface LateralMovement {
  source_machine: string;
  target_machine: string;
  user: string;
  event_id: number /* int */;
  timestamp: string;
  ip_address: string;
  severity: string;
  description: string;
  mitre_attack: string[];
}
export interface MultiAnalyzeResponse {
  machines: MachineInfo[];
  cross_machine_activity: CrossMachineActivity[];
  lateral_movement: LateralMovement[];
  summary: string;
  suspicious_count: number /* int */;
  analysis_id: string;
}

//////////
// source: handlers_persistence.go

export interface PersistenceHandler {
}
export interface DetectorConfig {
  name: string;
  enabled: boolean;
  description: string;
  technique: string;
  category: string;
}
export interface DetectionCache {
}
export interface DetectRequest {
  category: string;
  technique: string;
}
export interface DetectResponse {
  detections: (EnrichedDetection | undefined)[];
  summary: { [key: string]: any};
  duration: string;
  total_count: number /* int */;
  cached?: boolean;
}
export interface EnrichedDetection {
  id: string;
  time: string /* RFC3339 */;
  technique: string;
  category: string;
  severity: string;
  title: string;
  description: string;
  evidence: { [key: string]: any};
  mitre_ref: string[];
  recommended_action: string;
  false_positive_risk: string;
  explanation: string;
  recommendation: string;
  real_case: string;
}
export interface DetectorConfigUpdate {
  detectors: {
    name: string;
    enabled: boolean;
  }[];
}
export interface PersistenceRuleInfo {
  name: string;
  description: string;
  technique: string;
  category: string;
  enabled: boolean;
  event_ids: number /* int32 */[];
  patterns: string[];
  whitelist: string[];
  builtin_whitelist?: string[];
  builtin_dll_whitelist?: string[];
  builtin_clsids_whitelist?: string[];
  whitelist_type?: string;
}
export interface PersistenceRuleUpdate {
  name: string;
  enabled?: boolean;
  event_ids?: number /* int32 */[];
  patterns?: string[];
  whitelist?: string[];
  suspicious_indicators?: string[];
}
export interface WhitelistResponse {
  name: string;
  category: string;
  user_whitelist: string[];
  builtin_whitelist: string[];
  builtin_dll_whitelist: string[];
  builtin_clsids_whitelist: string[];
  whitelist_type: string;
}
export interface WhitelistUpdate {
  name: string;
  whitelist?: string[];
  dll_whitelist?: string[];
  clsids_whitelist?: string[];
}

//////////
// source: handlers_policy.go

export interface PolicyHandler {
}
export interface PolicyTemplateRequest {
  name: string;
  params: { [key: string]: string};
}
export interface PolicyTemplateInfo {
  name: string;
  description: string;
  policy_type: string;
  parameters: ParameterInfo[];
  time_window: string;
  enabled: boolean;
  priority: number /* int */;
  mitre_mapping?: string[];
}
export interface ParameterInfo {
  name: string;
  description: string;
  default?: string;
  required: boolean;
  type: string;
  options?: string[];
}
export interface CreateCustomPolicyRequest {
  name: string;
  description: string;
  policy_type: string;
  parameters: ParameterInfo[];
  conditions: ConditionInfo[];
  actions: ActionInfo[];
  time_window: number /* int */;
  enabled: boolean;
  priority: number /* int */;
  mitre_mapping: string[];
}
export interface ConditionInfo {
  field: string;
  operator: string;
  value: any;
}
export interface ActionInfo {
  type: string;
  parameters: { [key: string]: any};
}

//////////
// source: handlers_query.go

export interface QueryHandler {
}
export interface QueryRequest {
  sql: string;
  limit: number /* int */;
  offset: number /* int */;
}
export interface QueryResponse {
  columns: string[];
  rows: { [key: string]: any}[];
  count: number /* int */;
  total: number /* int */;
}
export interface TableInfo {
  name: string;
  columns: ColumnInfo[];
  count: number /* int64 */;
}
export interface ColumnInfo {
  name: string;
  type: string;
  not_null: boolean;
}
export interface QuickQuery {
  name: string;
  category: string;
  description: string;
  sql: string;
  table: string;
}

//////////
// source: handlers_reports.go

export interface ReportsHandler {
}
export interface ReportRequest {
  type: string;
  format: string;
  language: string; // "en" or "zh"
  start_time: string;
  end_time: string;
  include_raw: boolean;
  include_ioc: boolean;
  include_mitre: boolean;
  compression: boolean;
  title: string;
  description: string;
}
export interface ReportInfo {
  id: string;
  type: string;
  format: string;
  title: string;
  description: string;
  status: string;
  generated_at: string /* RFC3339 */;
  completed_at?: string /* RFC3339 */;
  file_path?: string;
  file_size?: number /* int64 */;
  error?: string;
}
export interface ReportContent {
  summary?: ReportSummary;
  alerts?: (ReportAlert | undefined)[];
  events?: (ReportEvent | undefined)[];
  timeline?: (ReportTimeline | undefined)[];
  raw_events?: (any /* types.Event */ | undefined)[];
}
export interface ReportSummary {
  total_events: number /* int64 */;
  total_alerts: number /* int64 */;
  critical_alerts: number /* int64 */;
  high_alerts: number /* int64 */;
  medium_alerts: number /* int64 */;
  low_alerts: number /* int64 */;
  top_sources: { [key: string]: number /* int64 */};
  time_range: TimeRange;
}
export interface TimeRange {
  start: string /* RFC3339 */;
  end: string /* RFC3339 */;
}
export interface ReportAlert {
  id: number /* int64 */;
  rule_name: string;
  severity: string;
  message: string;
  count: number /* int64 */;
  first_seen: string /* RFC3339 */;
  last_seen: string /* RFC3339 */;
  mitre_attack?: string[];
}
export interface ReportEvent {
  id: number /* int64 */;
  timestamp: string /* RFC3339 */;
  event_id: number /* int32 */;
  level: string;
  source: string;
  log_name: string;
  computer: string;
  message: string;
}
export interface ReportTimeline {
  timestamp: string /* RFC3339 */;
  type: string;
  source: string;
  message: string;
  severity?: string;
}
export interface TemplateRequest {
  name: string;
  content: string;
  description: string;
}

//////////
// source: handlers_rules.go

export interface RulesHandler {
}
export interface RuleInfo {
  id: string;
  name: string;
  description: string;
  enabled: boolean;
  severity: string;
  score: number /* float64 */;
  mitre_attack: string[];
  tags: string[];
  is_custom: boolean;
  event_ids?: number /* int32 */[];
  levels?: string[];
  filter?: FilterInfo;
  message?: string;
}
export interface FilterInfo {
  event_ids?: number /* int32 */[];
  levels?: string[];
  log_names?: string[];
  sources?: string[];
  computers?: string[];
  users?: string[];
  keywords?: string[];
  exclude_users?: string[];
  exclude_computers?: string[];
  ip_address?: string;
}
export interface RulesListResponse {
  rules: RuleInfo[];
  total_count: number /* int */;
  enabled_count: number /* int */;
  page?: number /* int */;
  page_size?: number /* int */;
  total_pages?: number /* int */;
}
export interface ListRulesRequest {
  Page: number /* int */;
  PageSize: number /* int */;
  Severity: string;
  Enabled?: boolean;
  Keyword: string;
}
export interface CreateRuleRequest {
  name: string;
  description: string;
  enabled: boolean;
  severity: string;
  score: number /* float64 */;
  mitre_attack: string[];
  tags: string[];
  event_ids: number /* int32 */[];
  levels: string[];
  filter?: FilterInfo;
  message: string;
}
export interface UpdateRuleRequest {
  description: string;
  enabled?: boolean;
  severity: string;
  score?: number /* float64 */;
  mitre_attack: string[];
  tags: string[];
  event_ids: number /* int32 */[];
  levels: string[];
  filter?: FilterInfo;
  message: string;
}
export interface ValidateRuleRequest {
  rule: RuleInfo;
  content: string;
}
export interface ValidateRuleResponse {
  valid: boolean;
  errors?: string[];
  warnings?: string[];
}
export interface ImportRulesRequest {
  rules: RuleInfo[];
}
export interface ImportRulesResponse {
  imported: number /* int */;
  failed: number /* int */;
  errors?: string[];
}
export interface TemplateInfo {
  name: string;
  description: string;
  parameters: TemplateParamInfo[];
  is_template: boolean;
}
export interface TemplateParamInfo {
  name: string;
  description: string;
  default?: string;
  required: boolean;
  type: string;
  options?: string[];
}
export interface InstantiateTemplateRequest {
  name: string;
  params: { [key: string]: string};
}

//////////
// source: handlers_settings.go

export interface SettingsHandler {
}
export interface Settings {
  database_path: string;
  log_level: string;
  max_events: number /* int */;
  retention_days: number /* int */;
  enable_alerting: boolean;
  enable_live_collection: boolean;
  enable_auto_update: boolean;
  api_port: number /* int */;
  api_host: string;
  cors_enabled: boolean;
  max_import_file_size: number /* int */;
  export_directory: string;
  parser_workers: number /* int */;
  memory_limit: number /* int */;
  request_timeout: number /* int */;
}

//////////
// source: handlers_suppress.go

export interface SuppressHandler {
}
export interface SuppressRuleRequest {
  name: string;
  conditions: SuppressConditionReq[];
  duration: number /* int */;
  scope: string;
  enabled: boolean;
  expires_at: string;
}
export interface SuppressConditionReq {
  field: string;
  operator: string;
  value: any;
}
export interface SuppressRuleResponse {
  id: number /* int64 */;
  name: string;
  conditions: any /* types.SuppressCondition */[];
  duration: number /* int */;
  scope: string;
  enabled: boolean;
  expires_at: string;
  created_at: string;
}

//////////
// source: handlers_system.go

export interface SystemHandler {
}
export interface SystemInfo {
  hostname: string;
  domain: string;
  os_name: string;
  os_version: string;
  architecture: string;
  is_admin: boolean;
  timezone: string;
  local_time: string /* RFC3339 */;
  uptime_seconds: number /* int64 */;
  go_version: string;
  cpu_count: number /* int */;
  memory_total_gb: number /* float64 */;
  memory_free_gb: number /* float64 */;
  system_memory_total_gb: number /* float64 */;
  system_memory_free_gb: number /* float64 */;
  go_memory_usage_mb: number /* float64 */;
}
export interface MetricsResponse {
  total_events: number /* int64 */;
  total_alerts: number /* int64 */;
  events_per_minute: number /* float64 */;
  alerts_per_hour: number /* float64 */;
  uptime_seconds: number /* int64 */;
  cpu_count: number /* int */;
  go_version: string;
  memory_usage_mb: number /* float64 */;
  system_memory_total_mb: number /* float64 */;
  system_memory_free_mb: number /* float64 */;
}
export interface ProcessResponse {
  processes: (ProcessInfo | undefined)[];
  total: number /* int */;
}
export interface ProcessInfo {
  pid: number /* int32 */;
  ppid: number /* int32 */;
  name: string;
  exe: string;
  args: string;
  user: string;
  status: string;
  path: string;
  command_line: string;
  is_signed: boolean;
  signature?: SignatureInfo;
}
export interface SignatureInfo {
  status: string;
  issuer: string;
  subject: string;
  valid_from: string;
  valid_to: string;
  thumbprint: string;
}
export interface NetworkConnectionResponse {
  connections: (NetworkConnInfo | undefined)[];
  total: number /* int */;
}
export interface NetworkConnInfo {
  pid: number /* int */;
  protocol: string;
  local_addr: string;
  local_port: number /* int */;
  remote_addr: string;
  remote_port: number /* int */;
  state: string;
  process_name: string;
}
export interface EnvVarResponse {
  variables: (EnvVar | undefined)[];
  total: number /* int */;
}
export interface EnvVar {
  name: string;
  value: string;
  type: string;
}
export interface DLLResponse {
  modules: (DLLInfo | undefined)[];
  total: number /* int */;
}
export interface DLLInfo {
  process_id: number /* int32 */;
  process_name: string;
  name: string;
  path: string;
  size: number /* uint32 */;
  version: string;
  is_signed: boolean;
}
export interface ProcessDLLResponse {
  process_id: number /* int32 */;
  process_name: string;
  dlls: (DLLInfo | undefined)[];
  total: number /* int */;
}
export interface DriverResponse {
  drivers: (DriverInfo | undefined)[];
  total: number /* int */;
}
export interface DriverInfo {
  name: string;
  display_name: string;
  description: string;
  path: string;
  status: string;
}
export interface UserResponse {
  users: (UserInfo | undefined)[];
  total: number /* int */;
}
export interface UserInfo {
  name: string;
  sid: string;
  enabled: boolean;
  full_name: string;
  type: string;
  home_dir: string;
}
export interface RegistryPersistenceResponse {
  run_keys: (RegistryKeyInfo | undefined)[];
  services: (RegistryKeyInfo | undefined)[];
  ifeo: (RegistryKeyInfo | undefined)[];
  app_init_dlls: (RegistryKeyInfo | undefined)[];
  known_dlls: (RegistryKeyInfo | undefined)[];
  boot_execute: (RegistryKeyInfo | undefined)[];
  appcert_dlls: (RegistryKeyInfo | undefined)[];
  lsa_settings: (RegistryKeyInfo | undefined)[];
  shell_extensions: (RegistryKeyInfo | undefined)[];
  browser_helpers: (RegistryKeyInfo | undefined)[];
  startup_folders: (RegistryKeyInfo | undefined)[];
  total: number /* int */;
}
export interface RegistryKeyInfo {
  path: string;
  name: string;
  value: string;
  type: string;
}
export interface TaskResponse {
  tasks: (TaskInfo | undefined)[];
  total: number /* int */;
}
export interface TaskInfo {
  name: string;
  path: string;
  state: string;
  description?: string;
  author?: string;
}

//////////
// source: handlers_ueba.go

export interface UEBAHandler {
}
export interface UEBARequest {
  start_time: string;
  end_time: string;
  hours: number /* int */;
}
export interface UEBAResult {
  type: string;
  anomalies: (any /* ueba.AnomalyResult */ | undefined)[];
  total_anomaly: number /* int */;
  high_risk_count: number /* int */;
  medium_risk_count: number /* int */;
  duration: string;
}

//////////
// source: handlers_ui.go

export interface UIHandler {
}
export interface DashboardOverview {
  total_events: number /* int64 */;
  total_alerts: number /* int64 */;
  critical_alerts: number /* int64 */;
  high_alerts: number /* int64 */;
  medium_alerts: number /* int64 */;
  low_alerts: number /* int64 */;
  resolved_alerts: number /* int64 */;
  unresolved_alerts: number /* int64 */;
  events_last_24h: number /* int64 */;
  alerts_last_24h: number /* int64 */;
  database_size: string;
  event_sources: { [key: string]: number /* int64 */};
  top_alerts: (AlertSummary | undefined)[];
  recent_events: (EventSummary | undefined)[];
  alert_trend: (TrendPoint | undefined)[];
  risk_score: number /* float64 */;
}
export interface AlertSummary {
  id: number /* int64 */;
  rule_name: string;
  severity: string;
  message: string;
  count: number /* int */;
  first_seen: string /* RFC3339 */;
  last_seen: string /* RFC3339 */;
  is_resolved: boolean;
}
export interface EventSummary {
  id: number /* int64 */;
  event_id: number /* int32 */;
  timestamp: string /* RFC3339 */;
  source: string;
  computer: string;
  level: string;
  message: string;
}
export interface TrendPoint {
  date: string;
  count: number /* int64 */;
}
export interface GroupInfo {
  key: string;
  severity?: string;
  count: number /* int64 */;
  first_seen: string /* RFC3339 */;
  last_seen: string /* RFC3339 */;
}
export interface EventIDCount {
  event_id: number /* int32 */;
  count: number /* int64 */;
}
