// Code generated by tygo. DO NOT EDIT.

//////////
// source: alert.go

export type Severity = string;
export const SeverityCritical: Severity = "critical";
export const SeverityHigh: Severity = "high";
export const SeverityMedium: Severity = "medium";
export const SeverityLow: Severity = "low";
export const SeverityInfo: Severity = "info";
export interface Alert {
  id: number /* int64 */;
  rule_name: string;
  severity: Severity;
  message: string;
  event_ids: number /* int32 */[];
  event_db_ids: number /* int64 */[];
  first_seen: string /* RFC3339 */;
  last_seen: string /* RFC3339 */;
  count: number /* int */;
  mitre_attack?: string[];
  resolved: boolean;
  resolved_time?: string /* RFC3339 */;
  notes?: string;
  false_positive: boolean;
  log_name: string;
  rule_score: number /* float64 */;
}
export interface AlertStats {
  total: number /* int64 */;
  by_severity: { [key: string]: number /* int64 */};
  by_status: { [key: string]: number /* int64 */};
  by_rule: (RuleCount | undefined)[];
  trend: (TrendPoint | undefined)[];
  avg_per_day: number /* float64 */;
  rule_score_avg: number /* float64 */;
}
export interface RuleCount {
  rule_name: string;
  count: number /* int64 */;
  percentage: number /* float64 */;
}
export interface TrendPoint {
  date: string;
  count: number /* int64 */;
}
export interface AlertTrend {
  daily: (TrendPoint | undefined)[];
  weekly: (TrendPoint | undefined)[];
  by_hour: (TrendPoint | undefined)[];
  by_day_of_week: (TrendPoint | undefined)[];
}
export interface AlertUpgradeRule {
  id: number /* int64 */;
  name: string;
  condition: string;
  threshold: number /* int */;
  new_severity: Severity;
  notify: boolean;
  enabled: boolean;
}
export interface SuppressRule {
  id: number /* int64 */;
  name: string;
  conditions: SuppressCondition[];
  duration: number /* milliseconds */;
  scope: string;
  enabled: boolean;
  expires_at?: string /* RFC3339 */;
  created_at: string /* RFC3339 */;
}
export interface SuppressCondition {
  field: string;
  operator: string;
  value: any;
}
export interface CorrelationResult {
  id: string;
  rule_name: string;
  description: string;
  severity: Severity;
  events: (Event | undefined)[];
  start_time: string /* RFC3339 */;
  end_time: string /* RFC3339 */;
  mitre_attack?: string[];
}
export interface AlertStatsData {
  TotalCount: number /* int64 */;
  BySeverity: { [key: string]: number /* int64 */};
  ByStatus: { [key: string]: number /* int64 */};
  ByRule: { [key: string]: number /* int64 */};
  TopRules: (RuleCount | undefined)[];
  AvgPerDay: number /* float64 */;
  RuleScoreAvg: number /* float64 */;
}
export interface AttackChain {
  id: string;
  event_ids: number /* int64 */[];
  start_time: string /* RFC3339 */;
  end_time: string /* RFC3339 */;
  severity: Severity;
  description: string;
  technique: string;
  events: (Event | undefined)[];
}

//////////
// source: errors.go

export type ErrorCode = string;
export const ErrCodeSuccess: ErrorCode = "SUCCESS";
export const ErrCodeInternalError: ErrorCode = "INTERNAL_ERROR";
export const ErrCodeInvalidParam: ErrorCode = "INVALID_PARAM";
export const ErrCodeInvalidRequest: ErrorCode = "INVALID_REQUEST";
export const ErrCodeInvalidQuery: ErrorCode = "INVALID_QUERY";
export const ErrCodeNotFound: ErrorCode = "NOT_FOUND";
export const ErrCodeEventNotFound: ErrorCode = "EVENT_NOT_FOUND";
export const ErrCodeAlertNotFound: ErrorCode = "ALERT_NOT_FOUND";
export const ErrCodeAlertAlreadyResolved: ErrorCode = "ALERT_ALREADY_RESOLVED";
export const ErrCodeUnauthorized: ErrorCode = "UNAUTHORIZED";
export const ErrCodeParseFailed: ErrorCode = "PARSE_FAILED";
export const ErrCodeImportFailed: ErrorCode = "IMPORT_FAILED";
export const ErrCodeFileNotFound: ErrorCode = "FILE_NOT_FOUND";
export const ErrCodeFileLocked: ErrorCode = "FILE_LOCKED";
export const ErrCodeInvalidFormat: ErrorCode = "INVALID_FORMAT";
export const ErrCodeDBError: ErrorCode = "DB_ERROR";
export const ErrCodeDBReadOnly: ErrorCode = "DB_READ_ONLY";
export const ErrCodeRuleInvalid: ErrorCode = "RULE_INVALID";
export const ErrCodeRuleNotFound: ErrorCode = "RULE_NOT_FOUND";
export const ErrCodeRuleDisabled: ErrorCode = "RULE_DISABLED";
export const ErrCodeSearchFailed: ErrorCode = "SEARCH_FAILED";
export const ErrCodeResultTooLarge: ErrorCode = "RESULT_TOO_LARGE";
export const ErrCodeHashMismatch: ErrorCode = "HASH_MISMATCH";
export const ErrCodeSignatureInvalid: ErrorCode = "SIGNATURE_INVALID";
export const ErrCodeNotSupported: ErrorCode = "NOT_SUPPORTED";
export interface WinError {
  Code: ErrorCode;
  Message: string;
  Cause: any;
}
export interface ParseError {
  WinError?: WinError;
  FilePath: string;
  Line: number /* int */;
}
export interface ValidationError {
  WinError?: WinError;
  Field: string;
  Value: any;
}
export interface AggregateError {
  Errors: any[];
}

//////////
// source: event.go

export type EventLevel = string;
export const EventLevelCritical: EventLevel = "Critical";
export const EventLevelError: EventLevel = "Error";
export const EventLevelWarning: EventLevel = "Warning";
export const EventLevelInfo: EventLevel = "Info";
export const EventLevelVerbose: EventLevel = "Verbose";
export interface Event {
  id: number /* int64 */;
  timestamp: string /* RFC3339 */;
  event_id: number /* int32 */;
  level: EventLevel;
  source: string;
  log_name: string;
  computer: string;
  user?: string;
  user_sid?: string;
  message: string;
  raw_xml?: string;
  session_id?: string;
  ip_address?: string;
  import_time: string /* RFC3339 */;
  import_id?: number /* int64 */;
  extracted_fields?: { [key: string]: any};
}
export interface EventIDCount {
  event_id: number /* int32 */;
  count: number /* int64 */;
}
export interface LevelDistribution {
  level: EventLevel;
  count: number /* int64 */;
}
export interface LogNameDistribution {
  log_name: string;
  count: number /* int64 */;
}

//////////
// source: result.go

export interface ImportResult {
  Success: boolean;
  TotalFiles: number /* int */;
  FilesImported: number /* int */;
  FilesFailed: number /* int */;
  EventsImported: number /* int64 */;
  EventsFailed: number /* int64 */;
  Duration: number /* milliseconds */;
  Errors: (ImportError | undefined)[];
}
export interface ImportError {
  file_path: string;
  error: string;
}
export interface SearchRequest {
  keywords: string;
  keyword_mode: string;
  regex: boolean;
  event_ids: number /* int32 */[];
  levels: number /* int */[];
  log_names: string[];
  sources: string[];
  users: string[];
  computers: string[];
  start_time?: string /* RFC3339 */;
  end_time?: string /* RFC3339 */;
  page: number /* int */;
  page_size: number /* int */;
  sort_by: string;
  sort_order: string;
  highlight: boolean;
}
export interface SearchResponse {
  events: (Event | undefined)[];
  total: number /* int64 */;
  page: number /* int */;
  page_size: number /* int */;
  total_pages: number /* int */;
  query_time_ms: number /* int64 */;
}
export interface CollectResult {
  Success: boolean;
  OutputPath: string;
  FileCount: number /* int */;
  TotalSize: number /* int64 */;
  Duration: number /* milliseconds */;
  Hash: string;
  Errors: any[];
}
export interface CollectOptions {
  OutputPath: string;
  IncludeLogs: boolean;
  IncludePrefetch: boolean;
  IncludeShimcache: boolean;
  IncludeAmcache: boolean;
  IncludeUserassist: boolean;
  IncludeRegistry: boolean;
  IncludeTasks: boolean;
  IncludeSystemInfo: boolean;
  Compress: boolean;
  CompressLevel: number /* int */;
  CalculateHash: boolean;
  Password: string;
  ExcludePatterns: string;
  Workers: number /* int */;
}
export interface VerifyResult {
  file_path: string;
  sha256: string;
  expected?: string;
  match: boolean;
}
export interface AnalyzeResult {
  type: string;
  results: any;
  summary: string;
}
export interface HealthStatus {
  status: string;
  database: string;
  storage: string;
  uptime: number /* milliseconds */;
  timestamp: string /* RFC3339 */;
}
export interface Pagination {
  page: number /* int */;
  page_size: number /* int */;
  total: number /* int64 */;
}
export interface TimeRange {
  start: string /* RFC3339 */;
  end: string /* RFC3339 */;
}

//////////
// source: rule.go

export type LogicalOp = string;
export const OpAnd: LogicalOp = "AND";
export const OpOr: LogicalOp = "OR";
export interface BaseRule {
  name: string;
  description: string;
  severity: Severity;
  mitre_attack?: string[];
  enabled: boolean;
  tags?: string[];
}
export interface Filter {
  field: string;
  operator: string;
  value: any;
}
export interface AlertRule {
  BaseRule: BaseRule;
  event_ids: number /* int32 */[];
  filters?: Filter[];
  condition_op: LogicalOp;
  group_by?: string;
  threshold: number /* int */;
  time_window: number /* milliseconds */;
  rule_score: number /* float64 */;
  recommendations?: string[];
}
export interface Condition {
  event_ids: number /* int32 */[];
  log_source?: string;
  filters?: Filter[];
  aggregation?: string;
}
export interface CorrelationRule {
  BaseRule: BaseRule;
  time_window: number /* milliseconds */;
  conditions: Condition[];
  join_field?: string;
  cross_bucket: boolean;
}
export type Rule = any;
export interface RuleScore {
  name: string;
  score: number /* float64 */;
  weight: number /* float64 */;
}
export interface RuleMetadata {
  author?: string;
  version?: string;
  created_at?: string /* RFC3339 */;
  updated_at?: string /* RFC3339 */;
  category?: string;
  industry?: string;
  references?: string[];
}
export type RuleAlias = AlertRule | CorrelationRule;

//////////
// source: system.go

export interface SystemInfo {
  hostname: string;
  domain: string;
  os_name: string;
  os_version: string;
  architecture: string;
  is_admin: boolean;
  timezone: string;
  local_time: string /* RFC3339 */;
  uptime: number /* milliseconds */;
  cpu_cores: number /* int */;
  cpu_model: string;
  memory_total: number /* uint64 */;
  memory_free: number /* uint64 */;
  boot_time: string /* RFC3339 */;
}
export interface SignatureInfo {
  status: string;
  issuer: string;
  subject: string;
  valid_from: string;
  valid_to: string;
  thumbprint: string;
  serial_number: string;
}
export interface ProcessInfo {
  pid: number /* int32 */;
  name: string;
  ppid: number /* int32 */;
  path: string;
  command_line: string;
  user: string;
  cpu_percent: number /* float64 */;
  memory_mb: number /* float64 */;
  start_time: string /* RFC3339 */;
  signature?: SignatureInfo;
  is_signed: boolean;
  hash_sha256: string;
  is_elevated: boolean;
}
export interface NetworkConnection {
  protocol: string;
  local_addr: string;
  local_port: number /* int */;
  remote_addr: string;
  remote_port: number /* int */;
  state: string;
  pid: number /* int32 */;
  process_name: string;
  created: string /* RFC3339 */;
}
export interface UserAccount {
  sid: string;
  name: string;
  domain: string;
  full_name: string;
  type: string;
  enabled: boolean;
  last_login: string /* RFC3339 */;
  password_age: number /* milliseconds */;
  password_expires: boolean;
  home_dir: string;
  profile_path: string;
}
export interface RegistryInfo {
  path: string;
  name: string;
  value: string;
  type: string;
  source: string;
  enabled: boolean;
}
export interface RegistryPersistence {
  run_keys: (RegistryInfo | undefined)[];
  user_init: (RegistryInfo | undefined)[];
  task_scheduler: (RegistryInfo | undefined)[];
}
export interface ScheduledTask {
  name: string;
  path: string;
  state: string;
  last_run: string /* RFC3339 */;
  next_run: string /* RFC3339 */;
  last_result: number /* int */;
  description: string;
  author: string;
  actions: TaskAction[];
  triggers: TaskTrigger[];
}
export interface TaskAction {
  type: string;
  path: string;
  args: string;
}
export interface TaskTrigger {
  type: string;
  start: string /* RFC3339 */;
}
export interface DriverInfo {
  name: string;
  description: string;
  type: string;
  status: string;
  started: boolean;
  file_path: string;
  hash_sha256: string;
  signature: string;
  signer: string;
}
export interface EnvInfo {
  key: string;
  value: string;
  type: string;
}
export interface DLLModule {
  process_id: number /* int32 */;
  process_name: string;
  base_address: string;
  size: number /* uint32 */;
  path: string;
  hash_sha256: string;
  version: string;
  signature?: SignatureInfo;
  is_signed: boolean;
}
export interface WMIProvider {
  name: string;
  namespace: string;
  clsid: string;
  enabled: boolean;
  owner: string;
}
export interface WMISubscription {
  name: string;
  namespace: string;
  filter: string;
  consumer: string;
  type: string;
  created: string /* RFC3339 */;
  last_modified: string /* RFC3339 */;
}
export interface PrefetchEntry {
  name: string;
  path: string;
  last_run_time: string /* RFC3339 */;
  run_count: number /* int */;
  collected_at: string /* RFC3339 */;
}
export interface ShimCacheEntry {
  path: string;
  last_modified: string /* RFC3339 */;
  execution_time: string /* RFC3339 */;
  collected_at: string /* RFC3339 */;
}
export interface AmcacheEntry {
  path: string;
  sha1: string;
  binary_type: string;
  collected_at: string /* RFC3339 */;
}
export interface UserAssistEntry {
  name: string;
  path: string;
  focus_count: number /* int */;
  time_focused: number /* int64 */;
  last_used: string /* RFC3339 */;
  collected_at: string /* RFC3339 */;
}
export interface USNJournalEntry {
  name: string;
  path: string;
  reason: string;
  timestamp: string /* RFC3339 */;
  collected_at: string /* RFC3339 */;
}

//////////
// source: time.go

export interface TimeFilter {
  Start: string /* RFC3339 */;
  End: string /* RFC3339 */;
}
